name: Black
on: [ push, pull_request ]
jobs:
  black:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Run Black Formatting
        uses: psf/black@stable
        with:
          options: "."
          src: "."

      - name: Check for changes
        run: |
          git diff --quiet || echo "HAS_CHANGES=true" >> $GITHUB_ENV

      - name: Commit Formatting to Repository
        if: env.HAS_CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Black formatting changes
          commit_options: '--no-verify --signoff'